### ISSUE TITLE
能否两个分支Node指向最终一个Node

### ISSUE THREAD

**Issue by SamHz** [bosscheng/vue-draggable-workflow#6]
目前如果有条件语句时，出现一个或多个分开的节点，能不能加一个分支合并的方法？

**Comment by bosscheng** [comment]
加是可以加，但是交互上面不知道如何设计。你有要的建议嘛。

**Comment by SamHz** [comment]
@bosscheng 可否在点击或拖拽到些处的点击时去指定的Node上，下拉选项或者我试过拖拽加号是可以指向节点的，但无法合并，如能做个拖拽线到已有节点，这样功能就完善了。因为一个WF图如果多个结束节点好像不太对。不知可否做到。

**Comment by bosscheng** [comment]
@SamHz 我懂你的意思了，我考虑下吧。
