### ISSUE TITLE
What license is this code released under? / 此代码以什么许可证发布？

### ISSUE THREAD

**Issue by dflock** [bosscheng/vue-draggable-workflow#8]
Things that you create and don't specify a license for, are automatically copyrighted to you - and not re-usable by others without explicit permission for each use.

As far as I can see, there's no license specified for this repository, so anyone who wants to use it would need to get permission directly from you for each use.

Is this intentional? If not, you should specify the license, so others can use it.

------------------------------------------

您创建且未指定许可的内容将自动获得版权保护，未经他人明确许可，不得被他人重复使用。

据我所知，没有为该存储库指定许可证，因此任何想要使用它的人都需要直接从您那里获得每次使用的许可。

这是故意的吗？ 如果不是，则应指定许可证，以便其他人可以使用它。

**Comment by bosscheng** [comment]
tks
